(function(){
'use strict';
var c=window.CHECK_LT_CONFIG;if(!c||!c.version||!c.appUrl)throw new Error('Configuração do CHECK-SELT ausente ou inválida.');
var APP_URL=c.appUrl,deferred=null,reg=null,reloadAfterUpdate=false,slowTimer=null;
var $=function(id){return document.getElementById(id)};
var installButton=$('installButton'),installButtonText=$('installButtonText'),installHint=$('installHint'),openButton=$('openButton'),openButtonText=$('openButtonText'),introText=$('introText'),connectionBanner=$('connectionBanner'),connectionText=$('connectionText'),updateBanner=$('updateBanner'),updateText=$('updateText'),updateButton=$('updateButton'),launchOverlay=$('launchOverlay'),launchStatus=$('launchStatus'),launchLoader=$('launchLoader'),launchRetry=$('launchRetry'),installDialog=$('installDialog'),installInstructions=$('installInstructions');
var ua=navigator.userAgent||'',isIPadOS=navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1,isIOS=/iphone|ipad|ipod/i.test(ua)||isIPadOS,isAndroid=/android/i.test(ua),reduced=!!(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches),standalone=!!((window.matchMedia&&(window.matchMedia('(display-mode: standalone)').matches||window.matchMedia('(display-mode: fullscreen)').matches||window.matchMedia('(display-mode: minimal-ui)').matches))||navigator.standalone===true);
document.documentElement.setAttribute('data-pwa-version',c.version);try{localStorage.setItem('check-lt-pwa-version',c.version)}catch(e){}
function connection(){var off=navigator.onLine===false;connectionBanner.hidden=!off;if(off){connectionText.textContent='Sem conexão. O portal continua disponível; o ambiente online pode exigir internet.';installHint.textContent='O portal está disponível neste aparelho. Para abrir o ambiente online, reconecte-se ou tente mesmo assim.';openButtonText.textContent='Tentar abrir o CHECK-SELT'}else if(standalone){installHint.textContent='Aplicativo instalado neste aparelho.';openButtonText.textContent='Abrir CHECK-SELT'}else{installHint.textContent=isIOS?'No iPhone a instalação é manual, pelo Safari: o botão mostra os 3 passos.':'A instalação cria o ícone do CHECK-SELT na tela inicial.';openButtonText.textContent='Continuar sem instalar'}}
function showUpdate(msg){updateText.textContent=msg||'Nova versão do aplicativo disponível.';updateButton.disabled=false;updateButton.textContent='Atualizar';updateBanner.hidden=false}
function resetOverlay(){if(slowTimer)clearTimeout(slowTimer);launchStatus.textContent='Abrindo seu ambiente…';launchLoader.hidden=false;launchRetry.hidden=true;launchRetry.disabled=false;launchRetry.textContent='Tentar novamente'}
function hideOverlay(){if(slowTimer){clearTimeout(slowTimer);slowTimer=null}launchOverlay.classList.remove('show');launchOverlay.hidden=true;resetOverlay()}
function showOverlay(){resetOverlay();launchOverlay.hidden=false;requestAnimationFrame(function(){launchOverlay.classList.add('show')});slowTimer=setTimeout(function(){if(document.visibilityState==='visible'){launchStatus.textContent='Está demorando mais que o normal.';launchLoader.hidden=true;launchRetry.hidden=false}},8000)}
function go(replace){if(replace)location.replace(APP_URL);else location.assign(APP_URL)}
function openApp(replace){showOverlay();go(replace)}
/* Navegador embutido em outro aplicativo (WhatsApp, Instagram, Facebook...). No iOS esses
   navegadores não têm "Adicionar à Tela de Início"; no Android não têm "Instalar app". Como nem
   todos se identificam, o iOS também é tratado como "de app" quando o navegador não é o Safari —
   e, por cima disso, a nota final cobre o que a detecção errar. */
function navegadorDeApp(){if(/FBAN|FBAV|FB_IAB|Instagram|Line\/|MicroMessenger|Twitter|LinkedInApp|WhatsApp|Snapchat|Pinterest/i.test(ua))return true;if(isIOS)return!/Safari\//.test(ua)&&!/CriOS|FxiOS|EdgiOS|OPiOS/.test(ua);if(isAndroid)return/;\s?wv\)/.test(ua);return false}
function botaoCopiar(){return '<button type="button" class="install-copy" data-copiar>Copiar endereço do app</button>'}
function notaSafari(){return '<p class="install-note">Não encontrou “Adicionar à Tela de Início”? Então você não está no Safari. Abra este endereço no Safari e repita os passos.</p>'}
function instructions(){
  if(isIOS){
    if(navegadorDeApp())return '<p><b>Você está no navegador de outro aplicativo</b> (WhatsApp, Instagram, Facebook…). O iPhone não deixa instalar por aqui — é preciso abrir no Safari.</p><ol class="install-steps"><li>Toque em <b>⋯</b> (ou em <b>Abrir no navegador</b>) e escolha <b>Abrir no Safari</b>.</li><li>No Safari, toque em <b>Compartilhar</b> — o quadrado com a seta para cima.</li><li>Deslize a lista, escolha <b>Adicionar à Tela de Início</b> e toque em <b>Adicionar</b>.</li></ol>'+botaoCopiar()+notaSafari();
    return '<p>No iPhone a instalação é manual: a Apple não permite que um site se instale sozinho.</p><ol class="install-steps"><li>Toque em <b>Compartilhar</b> — o quadrado com a seta para cima, na barra de baixo.</li><li>Deslize a lista e escolha <b>Adicionar à Tela de Início</b>.</li><li>Toque em <b>Adicionar</b>, no canto de cima.</li></ol>'+notaSafari();
  }
  if(isAndroid){
    if(navegadorDeApp())return '<p><b>Você está no navegador de outro aplicativo</b> (WhatsApp, Instagram, Facebook…). A instalação não funciona por aqui.</p><ol class="install-steps"><li>Toque nos <b>três pontos ⋮</b> e escolha <b>Abrir no Chrome</b> (ou “Abrir no navegador”).</li><li>Já no Chrome, toque nos <b>três pontos ⋮</b>.</li><li>Escolha <b>Instalar app</b> e confirme.</li></ol>'+botaoCopiar();
    return '<p>No Chrome do Android:</p><ol class="install-steps"><li>Toque nos três pontos ⋮ no canto superior.</li><li>Escolha “Instalar app” ou “Adicionar à tela inicial”.</li><li>Toque em “Instalar” para criar o ícone.</li></ol>';
  }
  return '<p>Para instalar neste computador:</p><ol class="install-steps"><li>Procure o ícone de instalação na barra de endereço.</li><li>Escolha “Instalar CHECK-SELT”.</li><li>Confirme a instalação.</li></ol>'}
function enderecoDoPortal(){return location.href.split('#')[0].split('?')[0]}
function ligarCopiar(){var b=installInstructions.querySelector('[data-copiar]');if(!b)return;b.addEventListener('click',function(){var url=enderecoDoPortal();var aviso=function(t){b.textContent=t;setTimeout(function(){b.textContent='Copiar endereço do app'},3000)};var falhou=function(){b.textContent=url};try{if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(url).then(function(){aviso('Endereço copiado')},falhou);return}}catch(e){}falhou()})}
function showInstructions(){installInstructions.innerHTML=instructions();ligarCopiar();if(typeof installDialog.showModal==='function')installDialog.showModal();else installDialog.setAttribute('open','')}
function watch(r){reg=r;if(r.waiting&&navigator.serviceWorker.controller)showUpdate();r.addEventListener('updatefound',function(){var w=r.installing;if(!w)return;w.addEventListener('statechange',function(){if(w.state==='installed'&&navigator.serviceWorker.controller)showUpdate()})});r.update().catch(function(){})}
window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferred=e;installButtonText.textContent='Instalar CHECK-SELT';installHint.textContent='Toque no botão e confirme a instalação do ícone.'});
installButton.addEventListener('click',async function(){if(!deferred){showInstructions();return}installButton.disabled=true;installButtonText.textContent='Abrindo instalação…';try{await deferred.prompt();var choice=await deferred.userChoice;deferred=null;if(choice&&choice.outcome==='accepted'){installButtonText.textContent='Instalação confirmada';installHint.textContent='Abra o CHECK-SELT pelo novo ícone na tela inicial.'}else{installButtonText.textContent='Instalar CHECK-SELT';installHint.textContent='A instalação foi cancelada. Você pode tentar novamente.'}}catch(e){installButtonText.textContent='Como instalar';installHint.textContent='Use as instruções para instalar manualmente.';showInstructions()}finally{installButton.disabled=false}});
/* No desktop o Chrome MOVE a aba para a janela do app ao instalar, sem recarregar: o script que abre o app instalado nao roda de novo e o usuario ficava vendo o portal dentro do app. Por isso, ao detectar que a página virou janela de app (evento appinstalled ou mudança do display-mode), abre o ambiente na hora. No celular a aba continua aba, e o aviso de usar o novo ícone segue valendo. */
function virouAppInstalado(){return!!(window.matchMedia&&(window.matchMedia('(display-mode: standalone)').matches||window.matchMedia('(display-mode: fullscreen)').matches||window.matchMedia('(display-mode: minimal-ui)').matches))||navigator.standalone===true}
var jaAbriu=false;function abrirSeVirouApp(){if(jaAbriu)return;if(navigator.onLine!==false&&virouAppInstalado()){jaAbriu=true;openApp(true)}}
window.addEventListener('appinstalled',function(){deferred=null;installButtonText.textContent='Aplicativo instalado';installButton.disabled=true;installHint.textContent='Abra o CHECK-SELT pelo novo ícone na tela inicial.';setTimeout(abrirSeVirouApp,700);setTimeout(abrirSeVirouApp,2500)});
['standalone','fullscreen','minimal-ui'].forEach(function(m){if(!window.matchMedia)return;var q=window.matchMedia('(display-mode: '+m+')');if(q.addEventListener)q.addEventListener('change',abrirSeVirouApp);else if(q.addListener)q.addListener(abrirSeVirouApp)});
function refreshPortalState(){hideOverlay();connection();if(reg)reg.update().catch(function(){})}window.addEventListener('pageshow',refreshPortalState);document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible')refreshPortalState()});
openButton.href=APP_URL;openButton.addEventListener('click',function(e){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button>0)return;showOverlay()});
launchRetry.addEventListener('click',function(){launchRetry.disabled=true;launchRetry.textContent='Tentando novamente…';launchStatus.textContent='Tentando abrir o CHECK-SELT novamente…';launchLoader.hidden=false;go(true)});
updateButton.addEventListener('click',function(){updateButton.disabled=true;updateButton.textContent='Atualizando…';if(reg&&reg.waiting){reloadAfterUpdate=true;reg.waiting.postMessage({type:'SKIP_WAITING'});return}location.reload()});
window.addEventListener('online',connection);window.addEventListener('offline',connection);connection();
if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('controllerchange',function(){if(reloadAfterUpdate){location.reload();return}showUpdate('Nova versão pronta para usar.')});window.addEventListener('load',function(){var dir=location.pathname.substring(0,location.pathname.lastIndexOf('/')+1)||'/';navigator.serviceWorker.register(dir+'sw.js',{scope:dir,updateViaCache:'none'}).then(watch).catch(function(){})})}
var shortcut=new URLSearchParams(location.search).get('abrir')==='1';if(standalone){installButton.hidden=true;introText.textContent=navigator.onLine===false?'O portal continua disponível, mas o ambiente online do CHECK-SELT pode exigir conexão.':'Aplicativo instalado. Abrindo o CHECK-SELT…';openButtonText.textContent=navigator.onLine===false?'Tentar abrir o CHECK-SELT':'Abrir agora';if(navigator.onLine!==false)openApp(true)}else if(shortcut&&navigator.onLine!==false){openApp(true)}else if(isIOS){installButtonText.textContent=isIPadOS||/ipad/i.test(ua)?'Como instalar no iPad':'Como instalar no iPhone'}else if(isAndroid){installButtonText.textContent='Instalar CHECK-SELT';installHint.textContent='Toque para instalar. Se o Chrome não abrir automaticamente, mostramos os 3 passos.'}
}());
