(function(){
'use strict';
var c=window.CHECK_LT_CONFIG;if(!c||!c.version||!c.appUrl)throw new Error('Configuração do CHECK-LT ausente ou inválida.');
var APP_URL=c.appUrl,deferred=null,reg=null,reloadAfterUpdate=false,slowTimer=null;
var $=function(id){return document.getElementById(id)};
var installButton=$('installButton'),installButtonText=$('installButtonText'),installHint=$('installHint'),openButton=$('openButton'),openButtonText=$('openButtonText'),introText=$('introText'),connectionBanner=$('connectionBanner'),connectionText=$('connectionText'),updateBanner=$('updateBanner'),updateText=$('updateText'),updateButton=$('updateButton'),launchOverlay=$('launchOverlay'),launchStatus=$('launchStatus'),launchLoader=$('launchLoader'),launchRetry=$('launchRetry'),installDialog=$('installDialog'),installInstructions=$('installInstructions');
var ua=navigator.userAgent||'',isIPadOS=navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1,isIOS=/iphone|ipad|ipod/i.test(ua)||isIPadOS,isAndroid=/android/i.test(ua),reduced=!!(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches),standalone=!!((window.matchMedia&&(window.matchMedia('(display-mode: standalone)').matches||window.matchMedia('(display-mode: fullscreen)').matches||window.matchMedia('(display-mode: minimal-ui)').matches))||navigator.standalone===true);
document.documentElement.setAttribute('data-pwa-version',c.version);try{localStorage.setItem('check-lt-pwa-version',c.version)}catch(e){}
function connection(){var off=navigator.onLine===false;connectionBanner.hidden=!off;if(off){connectionText.textContent='Sem conexão. O portal continua disponível; o ambiente online pode exigir internet.';installHint.textContent='O portal está disponível neste aparelho. Para abrir o ambiente online, reconecte-se ou tente mesmo assim.';openButtonText.textContent='Tentar abrir o CHECK-LT'}else if(standalone){installHint.textContent='Aplicativo instalado neste aparelho.';openButtonText.textContent='Abrir CHECK-LT'}else{installHint.textContent='A instalação cria o ícone do CHECK-LT na tela inicial.';openButtonText.textContent='Continuar sem instalar'}}
function showUpdate(msg){updateText.textContent=msg||'Nova versão do aplicativo disponível.';updateButton.disabled=false;updateButton.textContent='Atualizar';updateBanner.hidden=false}
function resetOverlay(){if(slowTimer)clearTimeout(slowTimer);launchStatus.textContent='Abrindo seu ambiente…';launchLoader.hidden=false;launchRetry.hidden=true;launchRetry.disabled=false;launchRetry.textContent='Tentar novamente'}
function showOverlay(){resetOverlay();launchOverlay.hidden=false;requestAnimationFrame(function(){launchOverlay.classList.add('show')});slowTimer=setTimeout(function(){if(document.visibilityState==='visible'){launchStatus.textContent='Está demorando mais que o normal.';launchLoader.hidden=true;launchRetry.hidden=false}},8000)}
function go(replace){if(replace)location.replace(APP_URL);else location.assign(APP_URL)}
function openApp(replace){showOverlay();setTimeout(function(){go(replace)},reduced?0:180)}
function instructions(){if(isIOS)return '<p>No Safari, siga estes passos:</p><ol class="install-steps"><li>Toque no botão Compartilhar.</li><li>Escolha “Adicionar à Tela de Início”.</li><li>Toque em “Adicionar”.</li></ol>';if(isAndroid)return '<p>Se a instalação automática não aparecer:</p><ol class="install-steps"><li>Abra o menu do navegador.</li><li>Escolha “Instalar app” ou “Adicionar à tela inicial”.</li><li>Confirme a instalação.</li></ol>';return '<p>Para instalar neste computador:</p><ol class="install-steps"><li>Procure o ícone de instalação na barra de endereço.</li><li>Escolha “Instalar CHECK-LT”.</li><li>Confirme a instalação.</li></ol>'}
function showInstructions(){installInstructions.innerHTML=instructions();if(typeof installDialog.showModal==='function')installDialog.showModal();else installDialog.setAttribute('open','')}
function watch(r){reg=r;if(r.waiting&&navigator.serviceWorker.controller)showUpdate();r.addEventListener('updatefound',function(){var w=r.installing;if(!w)return;w.addEventListener('statechange',function(){if(w.state==='installed'&&navigator.serviceWorker.controller)showUpdate()})});r.update().catch(function(){})}
window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferred=e;installButtonText.textContent='Instalar aplicativo';installHint.textContent='Pronto para instalar com o ícone correto.'});
installButton.addEventListener('click',async function(){if(!deferred){showInstructions();return}installButton.disabled=true;installButtonText.textContent='Abrindo instalação…';try{await deferred.prompt();var choice=await deferred.userChoice;deferred=null;if(choice&&choice.outcome==='accepted'){installButtonText.textContent='Aplicativo instalado';installHint.textContent='Abra o CHECK-LT pelo novo ícone na tela inicial.'}else{installButtonText.textContent='Instalar aplicativo';installHint.textContent='A instalação foi cancelada. Você pode tentar novamente.'}}catch(e){installButtonText.textContent='Como instalar';installHint.textContent='Use as instruções para instalar manualmente.';showInstructions()}finally{installButton.disabled=false}});
window.addEventListener('appinstalled',function(){deferred=null;installButtonText.textContent='Aplicativo instalado';installButton.disabled=true;installHint.textContent='Abra o CHECK-LT pelo novo ícone na tela inicial.'});
openButton.href=APP_URL;openButton.addEventListener('click',function(e){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button>0)return;e.preventDefault();openApp(false)});
launchRetry.addEventListener('click',function(){launchRetry.disabled=true;launchRetry.textContent='Tentando novamente…';launchStatus.textContent='Tentando abrir o CHECK-LT novamente…';launchLoader.hidden=false;go(true)});
updateButton.addEventListener('click',function(){updateButton.disabled=true;updateButton.textContent='Atualizando…';if(reg&&reg.waiting){reloadAfterUpdate=true;reg.waiting.postMessage({type:'SKIP_WAITING'});return}location.reload()});
window.addEventListener('online',connection);window.addEventListener('offline',connection);connection();
if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('controllerchange',function(){if(reloadAfterUpdate){location.reload();return}showUpdate('Nova versão pronta para usar.')});window.addEventListener('load',function(){var dir=location.pathname.substring(0,location.pathname.lastIndexOf('/')+1)||'/';navigator.serviceWorker.register(dir+'sw.js',{scope:dir}).then(watch).catch(function(){})})}
var shortcut=new URLSearchParams(location.search).get('abrir')==='1';if(standalone){installButton.hidden=true;introText.textContent=navigator.onLine===false?'O portal continua disponível, mas o ambiente online do CHECK-LT pode exigir conexão.':'Aplicativo instalado. Abrindo o CHECK-LT…';openButtonText.textContent=navigator.onLine===false?'Tentar abrir o CHECK-LT':'Abrir agora';if(navigator.onLine!==false)openApp(true)}else if(shortcut&&navigator.onLine!==false){openApp(true)}else if(isIOS){installButtonText.textContent=isIPadOS||/ipad/i.test(ua)?'Como instalar no iPad':'Como instalar no iPhone'}else if(isAndroid){installButtonText.textContent='Como instalar no Android'}
}());
